<?xml version="1.0"?>
<robot name="jax" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Launch-provided args -->
  <xacro:arg name="controllers_yaml" default=""/>
  <xacro:arg name="jax_share" default=""/>

  <!-- Absolute mesh root -->
  <xacro:property name="mesh_root" value="$(arg jax_share)/meshes"/>

  <!-- =========================
       Basic parameters
       ========================= -->
  <xacro:property name="body_length" value="0.35"/>
  <xacro:property name="body_width"  value="0.16"/>
  <xacro:property name="body_height" value="0.08"/>

  <xacro:property name="hip_drop"  value="0.0001"/>
  <xacro:property name="thigh_len" value="0.13"/>
  <xacro:property name="calf_len"  value="0.12"/>

  <xacro:property name="hip_radius"   value="0.018"/>
  <xacro:property name="thigh_radius" value="0.014"/>
  <xacro:property name="calf_radius"  value="0.012"/>
  <xacro:property name="foot_radius"  value="0.010"/>

  <xacro:property name="hip_x" value="${body_length/2 - 0.065}"/>
  <xacro:property name="hip_y" value="${body_width/2  - 0.02}"/>
  <xacro:property name="hip_z" value="0.01"/>
  <xacro:property name="hip_x_shift" value="-0.02"/>  <!-- negative = move both front+rear backward -->

  <!-- Mesh correction rotations (rpy) -->
  <xacro:property name="hip_mesh_rpy"   value="0 0 0"/>
  <xacro:property name="thigh_mesh_rpy" value="0 0 0"/>
  <xacro:property name="calf_mesh_rpy"  value="0 0 0"/>
  <xacro:property name="foot_mesh_rpy"  value="0 0 0"/>

  <xacro:property name="hip_to_thigh_drop" value="0.04"/>

  <!-- Tuned hip mesh offsets (magnitudes) -->
  <xacro:property name="hip_mesh_y_mag" value="0.033"/>
  <xacro:property name="hip_mesh_z_offset" value="0.0"/>

  <xacro:property name="thigh_joint_y_mag" value="0.033"/>   <!-- outward -->
  <xacro:property name="thigh_joint_z_offset" value="0.0"/>

  <xacro:property name="calf_joint_y_mag" value="0.01"/>  <!-- tune this -->
  <xacro:property name="foot_joint_y_mag" value="-0.004"/>

  <!-- =========================
       Materials (RViz)
       ========================= -->
  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
  <material name="white"><color rgba="0.9 0.9 0.9 1"/></material>
  <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>

  <!-- =========================
       Simple inertial macros
       ========================= -->
  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${(mass/12.0) * (y*y + z*z)}"
        iyy="${(mass/12.0) * (x*x + z*z)}"
        izz="${(mass/12.0) * (x*x + y*y)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder" params="mass radius length axis">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:if value="${axis == 'z'}">
        <inertia
          ixx="${(mass/12.0) * (3*radius*radius + length*length)}"
          iyy="${(mass/12.0) * (3*radius*radius + length*length)}"
          izz="${0.5*mass*radius*radius}"
          ixy="0" ixz="0" iyz="0"/>
      </xacro:if>
      <xacro:if value="${axis != 'z'}">
        <inertia
          ixx="${0.5*mass*radius*radius}"
          iyy="${(mass/12.0) * (3*radius*radius + length*length)}"
          izz="${(mass/12.0) * (3*radius*radius + length*length)}"
          ixy="0" ixz="0" iyz="0"/>
      </xacro:if>
    </inertial>
  </xacro:macro>

  <!-- =========================
       Base link
       ========================= -->
  <link name="base_link">
    <visual name="base_visual">
      <origin xyz="0.005 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://${mesh_root}/base_link.stl"
              scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision name="base_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="2.0"/>
      <origin xyz="0.03 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${(2.0/12.0) * (body_width*body_width + body_height*body_height)}"
        iyy="${(2.0/12.0) * (body_length*body_length + body_height*body_height)}"
        izz="${(2.0/12.0) * (body_length*body_length + body_width*body_width)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <gravity>false</gravity>
  </gazebo>


  <!-- IMU frame -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
  </joint>

  <!-- =========================
       Leg macro with left/right mesh selection
       ========================= -->
  <xacro:macro name="leg" params="prefix x y z">

    <!-- Compute hip mesh Y offset inside macro (prefix is defined here) -->
    <xacro:property name="hip_mesh_y_offset" value="${hip_mesh_y_mag}"/>
    <xacro:if value="${'right' in prefix}">
      <xacro:property name="hip_mesh_y_offset" value="${-hip_mesh_y_mag}"/>
    </xacro:if>

    <xacro:property name="thigh_joint_y" value="${thigh_joint_y_mag}"/>
    <xacro:if value="${'right' in prefix}">
      <xacro:property name="thigh_joint_y" value="${-thigh_joint_y_mag}"/>
    </xacro:if>

    <xacro:property name="calf_joint_y" value="${calf_joint_y_mag}"/>
    <xacro:if value="${'right' in prefix}">
      <xacro:property name="calf_joint_y" value="${-calf_joint_y_mag}"/>
    </xacro:if>

    <xacro:property name="foot_joint_y" value="${foot_joint_y_mag}"/>
    <xacro:if value="${'right' in prefix}">
      <xacro:property name="foot_joint_y" value="${-foot_joint_y_mag}"/>
    </xacro:if>

    <!-- Choose left/right meshes based on prefix -->
    <xacro:property name="hip_mesh"   value="${'left' in prefix and 'left_hip.stl'   or 'right_hip.stl'}"/>
    <xacro:property name="thigh_mesh" value="${'left' in prefix and 'left_thigh.stl' or 'right_thigh.stl'}"/>
    <xacro:property name="calf_mesh"  value="${'left' in prefix and 'left_calf.stl'  or 'right_calf.stl'}"/>
    <xacro:property name="foot_mesh" value="foot.stl"/>

    <!-- Hip link -->
    <link name="${prefix}_hip_link">
      <visual name="${prefix}_hip_visual">
        <origin xyz="0 ${hip_mesh_y_offset} ${hip_mesh_z_offset}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://${mesh_root}/${hip_mesh}"
                scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>

      <collision name="${prefix}_hip_collision">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${hip_radius}" length="${hip_drop}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="0.10" radius="${hip_radius}" length="${hip_drop}" axis="z"/>
    </link>

    <gazebo reference="${prefix}_hip_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${prefix}_hip_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_hip_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-0.60" upper="0.60" effort="30.0" velocity="6.0"/>
      <dynamics damping="2.0" friction="0.2"/>
    </joint>

    <!-- Thigh link -->
    <link name="${prefix}_thigh_link">
      <visual name="${prefix}_thigh_visual">
        <origin xyz="0 0 0" rpy="${thigh_mesh_rpy}"/>
        <geometry>
          <mesh filename="file://${mesh_root}/${thigh_mesh}"
                scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision name="${prefix}_thigh_collision">
        <origin xyz="0 0 ${-thigh_len/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${thigh_radius}" length="${thigh_len}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="0.18" radius="${thigh_radius}" length="${thigh_len}" axis="x"/>
    </link>

    <gazebo reference="${prefix}_thigh_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}_thigh_joint" type="revolute">
      <parent link="${prefix}_hip_link"/>
      <child link="${prefix}_thigh_link"/>
      <origin xyz="0 ${thigh_joint_y} ${thigh_joint_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.20" upper="1.20" effort="40.0" velocity="6.0"/>
      <dynamics damping="2.0" friction="0.1"/>
    </joint>

    <!-- Calf link -->
    <link name="${prefix}_calf_link">
      <visual name="${prefix}_calf_visual">
        <origin xyz="0 0 0" rpy="${calf_mesh_rpy}"/>
        <geometry>
          <mesh filename="file://${mesh_root}/${calf_mesh}"
                scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="black"/>
      </visual>

      <!-- stable calf collision -->
      <collision name="${prefix}_calf_collision">
        <origin xyz="0 0 ${-calf_len/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${calf_radius}" length="${calf_len * 0.2}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="0.14" radius="${calf_radius}" length="${calf_len}" axis="x"/>
    </link>

    <gazebo reference="${prefix}_calf_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}_calf_joint" type="revolute">
      <parent link="${prefix}_thigh_link"/>
      <child link="${prefix}_calf_link"/>
      <origin xyz="0 ${calf_joint_y} ${-thigh_len}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.40" upper="0.0" effort="30.0" velocity="6.0"/>
      <dynamics damping="2.0" friction="0.1"/>
    </joint>

    <!-- Foot link -->
    <link name="${prefix}_foot_link">
      <visual name="${prefix}_foot_visual">
        <origin xyz="0 0 -0.005" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://${mesh_root}/${foot_mesh}"
                scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray"/>
      </visual>

      <collision name="${prefix}_foot_collision">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${foot_radius}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.03"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

   <gazebo reference="${prefix}_foot_link">
      <material>Gazebo/Grey</material>

      <!-- friction -->
      <mu1>1.5</mu1>
      <mu2>1.5</mu2>

      <!-- contact stiffness/damping (helps prevent “ice skating” and bouncing) -->
      <kp>100000.0</kp>
      <kd>1.0</kd>
    </gazebo>


    <joint name="${prefix}_foot_joint" type="fixed">
      <parent link="${prefix}_calf_link"/>
      <child link="${prefix}_foot_link"/>
      <!-- your tuned foot location -->
      <origin xyz="0.094 ${foot_joint_y} ${-calf_len + 0.025}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <!-- =========================
       Instantiate legs
       ========================= -->
  <xacro:leg prefix="front_left"  x="${ hip_x}" y="${ hip_y}" z="${hip_z}"/>
  <xacro:leg prefix="front_right" x="${ hip_x}" y="${-hip_y}" z="${hip_z}"/>
  <xacro:leg prefix="rear_left"   x="${-hip_x}" y="${ hip_y}" z="${hip_z}"/>
  <xacro:leg prefix="rear_right"  x="${-hip_x}" y="${-hip_y}" z="${hip_z}"/>

  <!-- =========================
       ros2_control for Gazebo
       ========================= -->
  <ros2_control name="JaxSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="front_left_hip_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_left_thigh_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_left_calf_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="front_right_hip_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_thigh_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_calf_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rear_left_hip_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_thigh_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_calf_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rear_right_hip_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_thigh_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_calf_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(arg controllers_yaml)</parameters>
    </plugin>
  </gazebo>

    <!-- =========================
       Gazebo initial joint positions (spawn stable)
       ========================= -->

  <!-- Front Left -->
  <gazebo reference="front_left_hip_joint"><initial_position>0.0</initial_position></gazebo>
  <gazebo reference="front_left_thigh_joint"><initial_position>0.6</initial_position></gazebo>
  <gazebo reference="front_left_calf_joint"><initial_position>-1.2</initial_position></gazebo>

  <!-- Front Right -->
  <gazebo reference="front_right_hip_joint"><initial_position>0.0</initial_position></gazebo>
  <gazebo reference="front_right_thigh_joint"><initial_position>0.6</initial_position></gazebo>
  <gazebo reference="front_right_calf_joint"><initial_position>-1.2</initial_position></gazebo>

  <!-- Rear Left -->
  <gazebo reference="rear_left_hip_joint"><initial_position>0.0</initial_position></gazebo>
  <gazebo reference="rear_left_thigh_joint"><initial_position>0.6</initial_position></gazebo>
  <gazebo reference="rear_left_calf_joint"><initial_position>-1.2</initial_position></gazebo>

  <!-- Rear Right -->
  <gazebo reference="rear_right_hip_joint"><initial_position>0.0</initial_position></gazebo>
  <gazebo reference="rear_right_thigh_joint"><initial_position>0.6</initial_position></gazebo>
  <gazebo reference="rear_right_calf_joint"><initial_position>-1.2</initial_position></gazebo>


</robot>
